### ISSUE TITLE
https://www.polymer-project.org/1.0/docs/devguide/styling.html

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/docs#1217]
I tried every crazy dash combination I could think of to change the background of a paper-toolbar

```css
paper-toolbar {...}

:host {
   --paper-toolbar {..}
   @apply(--paper-toolbar {..})
}
 --paper-toolbar {..}
@apply(--paper-toolbar {..})

--paper-toolbar-change-the-damn-background-god-damit
```

And this is how I end up changing my paper-toolbar lol

```css
paper-toolbar.paper-toolbar-0 {
                            background: transparent;
                            box-sizing: border-box;
                            color:black;   
                    }
```

PS no idea where this `.paper-toolbar-0` all of a sudden appeared in my chrome inspector, I definitely did not add it :)

I think the polymer team is heavily underestimating how many wrong ways I can come up with after reading the style documentation :p 

Allot of `try me` demo buttons are going to be needed in this doc because this new css stuff is maybe better than `::shadow` and `/deep/` but definitely not easier to know how it actually works.

**Comment by ebidel** [comment]
The new CSS stuff follows the rules in custom properties:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

The specific feature polymer adds is mixins..but you don't need that here. The [docs](https://elements.polymer-project.org/elements/paper-toolbar) say show `--paper-toolbar-background` is the property to update the bg color.

      paper-toolbar {
       --paper-toolbar-background: pink;
      }

http://jsbin.com/qanofafoho/edit?html,output (note I used custom-style because the styles are defined in the main document. If you're in an element, you don't need it.

**Comment by gertcuykens** [comment]
Great :) now add your jsbin link to the docs please because I am pretty sure it is going to be very helpful for others too who want to change a toolbar background.

Can't stress out enough how counter intuitive this is

```css
paper-toolbar {
   --paper-toolbar-background: pink;
 }
```
 instead of something like this

```css 
paper-toolbar {
   background: pink;
 }
```

**Comment by gertcuykens** [comment]
What about something like this for all elements

```css
paper-toolbar {
   --paper-background: pink;
 }
```
It looks the same but believe it or not it's much less confusing.
